---
- hosts: testservers
  tasks:
  - name: install epel repository && update system
    yum: name=epel-release state=present

  - name: install httpd
    yum: name=ntp state=present update_cache=yes

  - name: start httpd
    service: name=ntpd state=started enabled=yes

